from moviepy import editor
from PIL import Image, ImageDraw
import numpy as np


def generate_video(segment_frames: np.ndarray, im: Image, line_color=(255, 255, 211), bg_color=(125, 115, 119),
                   filename=''):
    """
    Generate the video with the following format:
    1. The source image
    2. Line segments start appearing
    3. Source image disappears and background changes
    4. Line segments interpolate to form a stick bug
    5. The stick bug video

    :param segment_frames: Array of segments in each frame generated by interp_segments()
    :param im: The source PIL Image
    :param line_color: RGB color for the line segments
    :param bg_color: RGB color for the background after the image disappears
    :param filename: Filename to save the video as. Leave blank to not save anything
    :return: MoviePy video clip
    """
    # list of clips in the video
    clips = []

    # first clip is the source image
    # center the image on a black background
    bg = Image.new('RGB', (1280, 720))
    scale = min(bg.width / im.width, bg.height / im.height)
    im = im.resize((int(im.width * scale), int(im.height * scale)))
    bg.paste(im, ((bg.width - im.width) // 2, (bg.height - im.height) // 2))
    im = bg
    clips.append(editor.ImageClip(np.array(im), duration=1))

    # line segments start appearing
    # draw a line, store the image clip, repeat for each line
    draw = ImageDraw.Draw(im)
    for segment in segment_frames[0]:
        draw.line(tuple(segment[:4]), fill=line_color, width=int(segment[4]))
        clips.append(editor.ImageClip(np.array(im), duration=0.33))

    # one more slightly longer clip after that
    clips.append(editor.ImageClip(np.array(im), duration=1))

    # redraw lines with gray background
    draw.rectangle([0, 0, 1280, 720], bg_color)
    for segment in segment_frames[0]:
        draw.line(tuple(segment[:4]), fill=line_color, width=int(segment[4]))
    clips.append(editor.ImageClip(np.array(im), duration=0.75))

    # use ImageSequenceClip for the line interpolation
    frames = []
    for i in range(segment_frames.shape[0]):
        draw.rectangle([0, 0, 1280, 720], bg_color)
        for segment in segment_frames[i]:
            draw.line(tuple(segment[:4]), fill=line_color, width=int(segment[4]))
        frames.append(np.asarray(im))
    clips.append(editor.ImageSequenceClip(frames, 30))

    # concatenate all of the clips and add the audio
    all_clips = editor.concatenate_videoclips(clips)
    all_clips = all_clips.set_audio(editor.AudioFileClip('audio.wav'))

    # add stick bug video to the clips and return video
    stick_bug_clip = editor.VideoFileClip('stick_bug.mp4').without_audio()
    final_clip = editor.concatenate_videoclips([all_clips, stick_bug_clip])
    if filename:
        final_clip.write_videofile(filename, fps=30)
    return final_clip
